## Operations using Numpy

### A. Mathematical Operations:

In [1]:
# import library
import numpy as np

In [2]:
arr = np.array([1,3,5,6,2])

#### 1. cos:

In [3]:
np.cos(arr) #calculates cos value

array([ 0.54030231, -0.9899925 ,  0.28366219,  0.96017029, -0.41614684])

#### 2. sin:

In [4]:
np.sin(arr) #calculates sin values

array([ 0.84147098,  0.14112001, -0.95892427, -0.2794155 ,  0.90929743])

#### 3. log:

In [5]:
np.log(arr) #calculates log valus of the elements in array

array([0.        , 1.09861229, 1.60943791, 1.79175947, 0.69314718])

#### 4. mean:

In [6]:
np.mean(arr) #calculates mean f an array

3.4

#### 5. median:

In [7]:
np.median(arr) #calculates median of an array

3.0

#### 6. std:

In [9]:
np.std(arr) #calculates standarad deviation of an array

1.854723699099141

#### 7. exp:

In [10]:
np.exp(arr) #calculates exponential of elements

array([  2.71828183,  20.08553692, 148.4131591 , 403.42879349,
         7.3890561 ])

### B. Binary operations:

In [11]:
arr1 = np.array([2,4,6,8,2])
arr2 = np.array([3,6,1,6,2])

#### 1. addition:

In [12]:
arr1+arr2 #add two arrays

array([ 5, 10,  7, 14,  4])

#### 2. subtraction:

In [13]:
arr1-arr2 #subtraction of arrays

array([-1, -2,  5,  2,  0])

#### 3. multiplication:

In [14]:
arr1*arr2 #multiplication of arrays

array([ 6, 24,  6, 48,  4])